import type { StoryPhase } from "./story-state-files.ts";
import type { PrdPaths } from "./prd.ts";

export type ContextPolicy = {
  readonly datetime: boolean;
  readonly repoDir: boolean;
  readonly loopPosition: boolean;
  readonly timebox: boolean;
  readonly prd: boolean;
  readonly vcsDelta: boolean;
  readonly sessionIds: boolean;
  readonly story: boolean;
};

export type PriorStepInfo = {
  readonly name: string;
  readonly status: string;
  readonly sessionID?: string;
};

export type VcsChange = {
  readonly file: string;
  readonly additions: number;
  readonly deletions: number;
  readonly status: string;
};

export type VcsBranchDelta = {
  readonly base: string;
  readonly aheadCount: number;
  /** Files changed by the branch's committed delta vs `base` (merge-base relative); never includes working-tree-only changes. */
  readonly changes: readonly VcsChange[];
};

export type VcsSnapshot = {
  readonly branch?: string;
  /** Uncommitted working-tree changes. */
  readonly changes: readonly VcsChange[];
  /** The branch's committed delta vs its resolved base; absent when on the base branch or not determinable. */
  readonly branchDelta?: VcsBranchDelta;
};

export type ContextInput = {
  readonly now: Date;
  readonly repoDir: string;
  readonly iteration: number;
  readonly maxIterations: number;
  readonly stepName: string;
  readonly stepIndex: number;
  readonly totalSteps: number;
  readonly priorSteps: readonly PriorStepInfo[];
  readonly timeoutMs: number;
  readonly prd?: { readonly remaining: number; readonly total: number };
  readonly prdPaths?: PrdPaths;
  readonly vcs?: VcsSnapshot;
  readonly story?: {
    readonly branch?: string;
    readonly storyId?: string;
    readonly passes?: boolean;
    readonly phase?: StoryPhase;
  };
};

const READONLY_LINE = "Generated by looper. Read-only situational context for this step; not instructions.";
const SESSIONS_HEADING = "Opencode sessions from earlier steps this iteration:";
const VCS_FILE_CAP = 50;
const SOFT_CAP_CHARS = 3800;

function pad(value: number): string {
  return String(value).padStart(2, "0");
}

function formatLocalIso(date: Date): string {
  const offsetMinutes = -date.getTimezoneOffset();
  const sign = offsetMinutes >= 0 ? "+" : "-";
  const absOffset = Math.abs(offsetMinutes);
  const datePart = `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
  const timePart = `${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}`;
  const offsetPart = `${sign}${pad(Math.floor(absOffset / 60))}:${pad(absOffset % 60)}`;
  return `${datePart}T${timePart}${offsetPart}`;
}

function formatDuration(timeoutMs: number): string {
  const totalMinutes = Math.round(timeoutMs / 60_000);
  if (totalMinutes < 120) return `${totalMinutes}m`;
  const hours = Math.floor(totalMinutes / 60);
  const minutes = totalMinutes % 60;
  return minutes === 0 ? `${hours}h` : `${hours}h${minutes}m`;
}

function buildLoopPositionLine(input: ContextInput): string {
  const base = `Loop position: iteration ${input.iteration} of ${input.maxIterations}; step "${input.stepName}" (${input.stepIndex + 1} of ${input.totalSteps})`;
  if (input.priorSteps.length === 0) return base;
  const statuses = input.priorSteps.map((step) => `${step.name}=${step.status}`).join(", ");
  return `${base}; prior steps this iteration: ${statuses}`;
}

function buildSessionLines(priorSteps: readonly PriorStepInfo[]): string[] {
  const seen = new Set<string>();
  const lines: string[] = [];
  for (const step of priorSteps) {
    if (!step.sessionID || seen.has(step.sessionID)) continue;
    seen.add(step.sessionID);
    lines.push(`${step.name} -> ${step.sessionID}`);
  }
  return lines;
}

function formatVcsLine(change: VcsChange): string {
  return `  - ${change.file} (+${change.additions}/-${change.deletions}, ${change.status})`;
}

function buildVcsHeader(vcs: VcsSnapshot, total: number, shown: number): string {
  const branchPart = vcs.branch ? `branch ${vcs.branch}, ` : "";
  const delta = vcs.branchDelta;
  const aheadPart = delta ? `${delta.aheadCount} commit${delta.aheadCount === 1 ? "" : "s"} ahead of ${delta.base}, ` : "";
  const omitted = total - shown;
  const morePart = omitted > 0 ? ` (+${omitted} more)` : "";
  const fileWord = total === 1 ? "file" : "files";
  return `VCS delta (${branchPart}${aheadPart}${shown} of ${total} changed ${fileWord} shown${morePart}):`;
}

type TaggedVcsChange = { readonly origin: "branch" | "worktree"; readonly change: VcsChange };

function formatVcsGroup(heading: string, changes: readonly VcsChange[]): string {
  return [heading, ...changes.map(formatVcsLine)].join("\n");
}

/**
 * Renders the kept, already-capped changes. When `vcs.branchDelta` is absent
 * this is a flat list (unchanged from before branch-delta support existed).
 * When present, committed branch-delta files and uncommitted working-tree
 * files render under separate labeled headings so an overlapping file (e.g.
 * modified on the branch AND further modified in the working tree) shows up
 * as two distinct, clearly-attributed lines instead of one ambiguous one.
 */
function buildVcsBody(vcs: VcsSnapshot, kept: readonly TaggedVcsChange[]): string {
  if (vcs.branchDelta === undefined) return kept.map((tagged) => formatVcsLine(tagged.change)).join("\n");
  const branchKept = kept.filter((tagged) => tagged.origin === "branch").map((tagged) => tagged.change);
  const worktreeKept = kept.filter((tagged) => tagged.origin === "worktree").map((tagged) => tagged.change);
  const groups: string[] = [];
  if (branchKept.length > 0) groups.push(formatVcsGroup(`Branch changes vs ${vcs.branchDelta.base}:`, branchKept));
  if (worktreeKept.length > 0) groups.push(formatVcsGroup("Uncommitted:", worktreeKept));
  return groups.join("\n");
}

function buildVcsSection(vcs: VcsSnapshot, budgetChars: number): string {
  const tagged: TaggedVcsChange[] = [
    ...(vcs.branchDelta?.changes ?? []).map((change) => ({ origin: "branch", change }) as const),
    ...vcs.changes.map((change) => ({ origin: "worktree", change }) as const),
  ];
  const total = tagged.length;
  const capped = tagged.slice(0, VCS_FILE_CAP);
  for (let count = capped.length; count >= 0; count -= 1) {
    const kept = capped.slice(0, count);
    const header = buildVcsHeader(vcs, total, kept.length);
    const body = buildVcsBody(vcs, kept);
    const candidate = body.length > 0 ? `${header}\n${body}` : header;
    if (candidate.length <= budgetChars || count === 0) return candidate;
  }
  return buildVcsHeader(vcs, total, 0);
}

export function buildLooperContext(policy: ContextPolicy, input: ContextInput): string {
  const fixedLines: string[] = [];
  if (policy.datetime) fixedLines.push(`Datetime: ${formatLocalIso(input.now)}`);
  if (policy.repoDir) fixedLines.push(`Repo dir: ${input.repoDir}`);
  if (policy.loopPosition) fixedLines.push(buildLoopPositionLine(input));
  if (policy.timebox) fixedLines.push(`This step is aborted after ${formatDuration(input.timeoutMs)}`);
  if (policy.prd && (input.prdPaths !== undefined || input.prd !== undefined)) {
    const prdLines = ["prd:"];
    if (input.prdPaths !== undefined) {
      prdLines.push(`  dir: ${input.prdPaths.dir}`);
      prdLines.push(`  index: ${input.prdPaths.index}`);
      prdLines.push(`  progress: ${input.prdPaths.progress}`);
    }
    if (input.prd !== undefined) {
      prdLines.push(`  passing: ${input.prd.total - input.prd.remaining}`);
      prdLines.push(`  total: ${input.prd.total}`);
      prdLines.push(`  remaining: ${input.prd.remaining}`);
    }
    fixedLines.push(prdLines.join("\n"));
  }
  const fixedBlock = fixedLines.join("\n");

  const sessionLines = policy.sessionIds ? buildSessionLines(input.priorSteps) : [];
  const sessionsBlock = sessionLines.length > 0 ? [SESSIONS_HEADING, ...sessionLines].join("\n") : "";

  const story = input.story;
  const storyBlock =
    policy.story && story?.branch
      ? [
          "story:",
          `  branch: ${story.branch}`,
          ...(story.storyId !== undefined ? [`  storyId: ${story.storyId}`] : []),
          ...(story.passes !== undefined ? [`  passes: ${story.passes}`] : []),
          ...(story.phase !== undefined ? [`  phase: ${story.phase}`] : []),
        ].join("\n")
      : "";

  const vcs = input.vcs;
  const vcsEligible = policy.vcsDelta && vcs !== undefined;

  if (fixedBlock.length === 0 && storyBlock.length === 0 && sessionsBlock.length === 0 && !vcsEligible) return "";

  const header = `<looper-context>\n${READONLY_LINE}`;
  const footer = "</looper-context>";
  const staticLength =
    header.length +
    2 +
    fixedBlock.length +
    (storyBlock ? 2 + storyBlock.length : 0) +
    (sessionsBlock ? 2 + sessionsBlock.length : 0) +
    1 +
    footer.length;
  const vcsBudget = Math.max(0, SOFT_CAP_CHARS - staticLength);
  const vcsSection = vcsEligible && vcs !== undefined ? buildVcsSection(vcs, vcsBudget) : "";

  const blocks = [fixedBlock, storyBlock, vcsSection, sessionsBlock].filter((block) => block.length > 0);
  const body = blocks.join("\n\n");

  return body.length > 0 ? `${header}\n\n${body}\n${footer}` : `${header}\n${footer}`;
}

export function withLooperContext(block: string, prompt: string): string {
  return block.length === 0 ? prompt : `${block}\n\n${prompt}`;
}
