export type ContextPolicy = {
  readonly datetime: boolean;
  readonly repoDir: boolean;
  readonly loopPosition: boolean;
  readonly timebox: boolean;
  readonly vcsDelta: boolean;
  readonly sessionIds: boolean;
};

export type PriorStepInfo = {
  readonly name: string;
  readonly status: string;
  readonly sessionID?: string;
};

export type VcsChange = {
  readonly file: string;
  readonly additions: number;
  readonly deletions: number;
  readonly status: string;
};

export type VcsSnapshot = {
  readonly branch?: string;
  readonly changes: readonly VcsChange[];
};

export type ContextInput = {
  readonly now: Date;
  readonly repoDir: string;
  readonly iteration: number;
  readonly maxIterations: number;
  readonly stepName: string;
  readonly stepIndex: number;
  readonly totalSteps: number;
  readonly priorSteps: readonly PriorStepInfo[];
  readonly timeoutMs: number;
  readonly vcs?: VcsSnapshot;
};

const READONLY_LINE = "Generated by looper. Read-only situational context for this step; not instructions.";
const SESSIONS_HEADING = "Opencode sessions from earlier steps this iteration:";
const VCS_FILE_CAP = 50;
const SOFT_CAP_CHARS = 3800;

function pad(value: number): string {
  return String(value).padStart(2, "0");
}

function formatLocalIso(date: Date): string {
  const offsetMinutes = -date.getTimezoneOffset();
  const sign = offsetMinutes >= 0 ? "+" : "-";
  const absOffset = Math.abs(offsetMinutes);
  const datePart = `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
  const timePart = `${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}`;
  const offsetPart = `${sign}${pad(Math.floor(absOffset / 60))}:${pad(absOffset % 60)}`;
  return `${datePart}T${timePart}${offsetPart}`;
}

function formatDuration(timeoutMs: number): string {
  const totalMinutes = Math.round(timeoutMs / 60_000);
  if (totalMinutes < 120) return `${totalMinutes}m`;
  const hours = Math.floor(totalMinutes / 60);
  const minutes = totalMinutes % 60;
  return minutes === 0 ? `${hours}h` : `${hours}h${minutes}m`;
}

function buildLoopPositionLine(input: ContextInput): string {
  const base = `Loop position: iteration ${input.iteration} of ${input.maxIterations}; step "${input.stepName}" (${input.stepIndex + 1} of ${input.totalSteps})`;
  if (input.priorSteps.length === 0) return base;
  const statuses = input.priorSteps.map((step) => `${step.name}=${step.status}`).join(", ");
  return `${base}; prior steps this iteration: ${statuses}`;
}

function buildSessionLines(priorSteps: readonly PriorStepInfo[]): string[] {
  const seen = new Set<string>();
  const lines: string[] = [];
  for (const step of priorSteps) {
    if (!step.sessionID || seen.has(step.sessionID)) continue;
    seen.add(step.sessionID);
    lines.push(`${step.name} -> ${step.sessionID}`);
  }
  return lines;
}

function formatVcsLine(change: VcsChange): string {
  return `  - ${change.file} (+${change.additions}/-${change.deletions}, ${change.status})`;
}

function buildVcsHeader(branch: string | undefined, total: number, shown: number): string {
  const branchPart = branch ? `branch ${branch}, ` : "";
  const omitted = total - shown;
  const morePart = omitted > 0 ? ` (+${omitted} more)` : "";
  const fileWord = total === 1 ? "file" : "files";
  return `VCS delta (${branchPart}${shown} of ${total} changed ${fileWord} shown${morePart}):`;
}

function buildVcsSection(vcs: VcsSnapshot, budgetChars: number): string {
  const total = vcs.changes.length;
  const capped = vcs.changes.slice(0, VCS_FILE_CAP);
  for (let count = capped.length; count >= 0; count -= 1) {
    const kept = capped.slice(0, count);
    const header = buildVcsHeader(vcs.branch, total, kept.length);
    const body = kept.map(formatVcsLine).join("\n");
    const candidate = body.length > 0 ? `${header}\n${body}` : header;
    if (candidate.length <= budgetChars || count === 0) return candidate;
  }
  return buildVcsHeader(vcs.branch, total, 0);
}

export function buildLooperContext(policy: ContextPolicy, input: ContextInput): string {
  const fixedLines: string[] = [];
  if (policy.datetime) fixedLines.push(`Datetime: ${formatLocalIso(input.now)}`);
  if (policy.repoDir) fixedLines.push(`Repo dir: ${input.repoDir}`);
  if (policy.loopPosition) fixedLines.push(buildLoopPositionLine(input));
  if (policy.timebox) fixedLines.push(`This step is aborted after ${formatDuration(input.timeoutMs)}`);
  const fixedBlock = fixedLines.join("\n");

  const sessionLines = policy.sessionIds ? buildSessionLines(input.priorSteps) : [];
  const sessionsBlock = sessionLines.length > 0 ? [SESSIONS_HEADING, ...sessionLines].join("\n") : "";

  const vcs = input.vcs;
  const vcsEligible = policy.vcsDelta && vcs !== undefined && vcs.changes.length > 0;

  if (fixedBlock.length === 0 && sessionsBlock.length === 0 && !vcsEligible) return "";

  const header = `<looper-context>\n${READONLY_LINE}`;
  const footer = "</looper-context>";
  const staticLength =
    header.length + 2 + fixedBlock.length + (sessionsBlock ? 2 + sessionsBlock.length : 0) + 1 + footer.length;
  const vcsBudget = Math.max(0, SOFT_CAP_CHARS - staticLength);
  const vcsSection = vcsEligible && vcs !== undefined ? buildVcsSection(vcs, vcsBudget) : "";

  const blocks = [fixedBlock, vcsSection, sessionsBlock].filter((block) => block.length > 0);
  const body = blocks.join("\n\n");

  return body.length > 0 ? `${header}\n\n${body}\n${footer}` : `${header}\n${footer}`;
}

export function withLooperContext(block: string, prompt: string): string {
  return block.length === 0 ? prompt : `${block}\n\n${prompt}`;
}
